services:
  asnparser:
    image: asnparser
    container_name: 'asnparser'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./ASNParser:/app/ASNParser
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=mydatabase;Username=myuser;Password=mypassword;
    networks:
      - app-network
      
  db:
    image: postgres:13
    container_name: 'asnparser-db'
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./util:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
